/package endpoint without authentication check
Alethon/ECE461_Part2 pull request #57
Opened 2023-04-28 19:49 UTC by Ishaan-Jain

2023-04-28 21:50 UTC, KevinMi2023p requested changes

2023-04-28 21:50 UTC, KevinMi2023p commented on api_paths/src/main/java/com/spring_rest_api/api_paths/service/PackageService.java
> +        return docSs.getData().toString();
This isn't going to return a JSON string format

2023-04-30 22:02 UTC, techtronix-868 approved these changes
Accepted Incoming Changes

2023-04-30 22:07 UTC, KevinMi2023p approved these changes

2023-04-30 22:07 UTC, merged